# Generated by Django 5.0.6 on 2024-06-05 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
