# Generated by Django 5.0.6 on 2024-06-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0003_delete_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usrname', models.CharField(max_length=100)),
                ('igfollowers', models.IntegerField()),
                ('fbFollowers', models.IntegerField()),
            ],
        ),
    ]
