# Generated by Django 5.0.6 on 2024-06-15 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0005_rename_igfollowers_followers_igfollowers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
        migrations.DeleteModel(
            name='UsrCredentials',
        ),
    ]
