# Generated by Django 5.0.6 on 2024-06-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meta', '0006_delete_followers_delete_usrcredentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igFollowers', models.IntegerField()),
                ('fbFollowers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UsrCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('llAT', models.CharField(max_length=500)),
                ('pgAT', models.CharField(max_length=500)),
                ('igUserId', models.IntegerField()),
                ('fbPageId', models.IntegerField()),
                ('appID', models.IntegerField()),
                ('appSecret', models.CharField(max_length=200)),
            ],
        ),
    ]
