# Generated by Django 5.0.6 on 2024-06-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0008_followers_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
