# Generated by Django 5.0.6 on 2024-06-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0009_delete_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('igFollowers', models.IntegerField()),
                ('fbFollowers', models.IntegerField()),
            ],
        ),
    ]
