# Generated by Django 5.0.6 on 2024-06-26 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0010_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='fbFollowers',
            new_name='fbfollowers',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='igFollowers',
            new_name='igfollowers',
        ),
        migrations.RenameField(
            model_name='usrcredentials',
            old_name='appID',
            new_name='appid',
        ),
        migrations.RenameField(
            model_name='usrcredentials',
            old_name='appSecret',
            new_name='appsecret',
        ),
        migrations.RenameField(
            model_name='usrcredentials',
            old_name='fbPageId',
            new_name='fbpageid',
        ),
        migrations.RenameField(
            model_name='usrcredentials',
            old_name='igUserId',
            new_name='iguserid',
        ),
        migrations.RenameField(
            model_name='usrcredentials',
            old_name='llAT',
            new_name='llat',
        ),
        migrations.RenameField(
            model_name='usrcredentials',
            old_name='pgAT',
            new_name='pgat',
        ),
    ]
